# Generated by Django 3.0.1 on 2019-12-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20191221_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
